### PR TITLE
generating input files from US Wind Turbine Database

### PR DESCRIPTION
**Pull request by kflemin**

### CODE REVIEW

**Comment by rafmudaf** [comment]
@kflemin Sorry for the delay in looking at this pull request, its quite cool!

Do you mind if I rebase this branch onto the current `develop`? There are some minor file structure changes that currently break `farm_processor.py` if its merged as is.

**Comment by kflemin** [comment]
go for it!

**Comment by rafmudaf** [comment]
Very cool. I have some work to do to clean up the plotting.
waverly_a

**Comment by rafmudaf** [comment]
@kflemin I made a few changes to the "typo fix" commit which update the example input files and directory structure. If you're ok with those changes, I'll hit the merge button.

**Comment by kflemin** [comment]
looks good!

**Comment by rafmudaf** [comment]
Thanks for this great addition @kflemin

**Pull request merged**
