### PR TITLE
Add yaw effect on ct

### PR DESCRIPTION
**Pull request by paulf81**
This commit adds a reduction effect on ct from yaw, re-using the pP parameter for now, to produce a better match to SOWFA

### CODE REVIEW

**Comment by rafmudaf** [comment]
does the curl model need to be modified as well? This line will include yaw twice
```
        # calculate the curled wake effects due to the yaw and tilt of the turbine
        Gamma_Yaw = vortex_strength * np.pi * D / 2 * Ct * \
            turbine.average_velocity * np.sin(yaw) * np.cos(yaw)**2```

**Comment by paulf81** [comment]
I'll have to defer to @jrannoni  and @bayc  on this one, but thanks for flagging @rafmudaf

**Comment by rafmudaf** [comment]
I'm adding a regression test with yaw for future reference

**Comment by bayc** [comment]
So after talking with @jrannoni and Tony, @rafmudaf is right in that the curled wake model is computing the effective Ct at the turbine with the cos(yaw)**2 present in the circulation calculation he posted above. So we think the best solution is to include @paulf81  change in turbine.py and remove the cos(yaw)**2 term from the Gamma_Yaw calculation.

**Comment by bayc** [comment]
This would also need to happen for the cos(tilt)**2 term in the Gamma_tilt calculation, but not sure @paulf81 if you want to include that in turbine.py as well.

**Comment by paulf81** [comment]
Yes, I think it is best in principle if the turbine handles entirely the computation of ct and cp, to allow methods like LUTs in the future, all the wake models should assume the Ct is final I think

**Comment by paulf81** [comment]
Ok, please check again all, I removed the double count from the curl code

**Comment by jrannoni** [comment]
Looks good to me.

**Comment by bayc** [comment]
Looks good!

**Pull request merged**
